### ISSUE TITLE
ExpatError: not well-formed (invalid token): line 1, column 49

### ISSUE THREAD

**Issue by kadmor** [pylabel-project/samples#1]
Hello, thanks for the repository. When trying to translate a dataset into a VOC-format, this error occurs. Working with an example (road.txt)

**Comment by alexheat** [comment]
Hello @kadmor will will take a look today. Could you share the road.txt file? That gave you this error?

**Comment by alexheat** [comment]
Hello @kadmor , please let us know how to repo this issue.
