### ISSUE TITLE
AttributeError: 'Labeler' object has no attribute 'UseBBoxWidget'

### ISSUE THREAD

**Issue by Daniel-R-Armstrong** [pylabel-project/samples#2]
I am trying to get your yolo2pylabeler.ipynb notebook to work either on colab or local. 
I was able to get the a jupyter-bbox-widget to work, as well as the "pylabeler.ipynb" example to run, but when I try to run ```dataset.labeler.UseBBoxWidget(image=img_filename)``` in the 'yolo2pylabeler.ipynb'  I get:"AttributeError: 
```
'Labeler' object has no attribute 'UseBBoxWidget"
```

**Comment by alexheat** [comment]
Hello @Daniel-R-Armstrong  I have fixed the issue that you found. Please see the latest version at https://github.com/pylabel-project/samples/blob/main/yolo2pylabeler.ipynb. 

I would love to hear any feedback that you have. I think it can be very handy to be able to edit annotations within a notebook. But I don't think a lot of people have try this feature yet.

**Comment by Daniel-R-Armstrong** [comment]
It works like a charm!!!! I think the work you have done here is pretty amazing. I have used several different label tools and putting a model in the loop is always such a pain.  Using it inside of notebooks is by fare the best tool that I can ask for, especially when you are incorporating active learning into your model development/refinement. I am so excited to incorporate active learning with your tool. Thank you for sharing this amazing tool with the world!!!!

**Comment by alexheat** [comment]
Thank you for the encouragement @Daniel-R-Armstrong. If you have any other feedback please let us know

**Comment by Daniel-R-Armstrong** [comment]
I guys at IceVision have made an amazing parser that allows you to build your own bounding box parser, I think adding a custom parser or giving users the ability to convert labels from a dataframe would be helpful. I have aggregated labels from several different dataset as well as my own labels and I am trying to load them into your dataset object but it is challenging since they are not in one of your supported formats.

**Comment by alexheat** [comment]
Hi @Daniel-R-Armstrong . Happy holidays. You should be able to add things directly to the dataframe that is used by the pylable dataset object. It is accessible as dataset.df. You can see this file to see how items are added to the dataset in general https://github.com/pylabelalpha/pylabel/blob/main/pylabel/importer.py. I would be happy to help you more with your project to create documentation or a feature to help people do what you are trying to do. If you want to contact me directly you should be able to see my contact info here https://github.com/pylabelalpha/pylabel/commits?author=alexheat 

I will look into the size feature of the bbox widget that you mentioned

**Comment by alexheat** [comment]
@Daniel-R-Armstrong , I was not sure what you meant by this comment: 'It might also be nice to add the size feature from the jupyter bbox widget(but this wasn't working when I tried, it was grayed out)' I am not familar with what size feature you are referring. Can you add a screenshot or repro steps? Thanks! Alex

**Comment by Daniel-R-Armstrong** [comment]
![image](https://user-images.githubusercontent.com/22450871/147667737-a120c4b7-1bc8-4d5a-9261-0e5069702b59.png)
It didn't work because it is not really as size as I would have thought is was just a attribute that you can add, but it doesn't appear to do anything.

**Comment by Daniel-R-Armstrong** [comment]
on that same line of thought it would be really nice to have the ability to zoom and pan around like other tools, but I have a feeling it would get a little complicated since you would have to resize the base64 image and the annotations. It might be possible to create three base64 images, small-med-large, and have a toggle to determine which one you are using.

**Comment by Daniel-R-Armstrong** [comment]
@alexheat I was looking into the importer, and I going to create my own importer, but if you create a custom parser like what is in ice vision it will give the user a set of tools that make using the importer a little easier(I still think their parser is a little confusing at 1st glance). I cant wait till the object detection community uses the same format. I find it really irritating having to change annotation format all the time, but if you have framework where users can modify any annotation format to a common format and back out if needed, it will be very helpful, roboflow does this but they charge way too much for their services. 

This is an example of using IceVisions custom parser
```
template_record = ObjectDetectionRecord()
Parser.generate_template(template_record)

class myParser(Parser):
    def __init__(self, template_record, data_dir):
        super().__init__(template_record=template_record)
        
        self.data_dir = data_dir
        self.df = pd.read_csv(data_dir / "annotations/annotations.csv", header=None, 
                              names=["filename","x1","y1","x2","y2","label","img_width","img_height"])
        self.class_map = ClassMap(list(self.df['label'].unique()))
        
    def __iter__(self) -> Any:
        for o in self.df.itertuples():
            yield o
        
    def __len__(self) -> int:
        return len(self.df)
        
    def record_id(self, o) -> Hashable:
        return o.filename
        
    def parse_fields(self, o, record, is_new):
        if is_new:
            record.set_filepath(self.data_dir / 'images' / o.filename)
            record.set_img_size(ImgSize(width=o.img_width, height=o.img_height))
            record.detection.set_class_map(self.class_map)
        
        record.detection.add_bboxes([BBox.from_xyxy(o.x1, o.y1, o.x2, o.y2)])
        record.detection.add_labels([o.label])
```        
```
# Data splitter
trn_fls = df[df.filename.str.contains('train')].filename.unique()
tst_fls = df[df.filename.str.contains('test')].filename.unique()
val_fls = df[df.filename.str.contains('val')].filename.unique()
data_splitter = FixedSplitter([trn_fls ,val_fls, tst_fls])
```
```
# Parser
parser = myParser(template_record,data_dir)
train_records, valid_records, test_records  = parser.parse(data_splitter=data_splitter, autofix=True)
```
it also autofixs the annotations which is really really handy, I have had lot of issues with annotations being incorrect or the conversion causing issues.

I was looking into a way to combine your project with Ice_vision for model in the loop as well as active learning to fee the model training data. I am picturing a way for a user to annotate a few examples, fine-tune a model, then review and refine the models annotations, then use active learning methods to choose additional images for labeling based on model uncertainty and some diversity, then iterating over these steps over and over again. 

If you had any tips, any input you had would be beneficial.
