### ISSUE TITLE
anyway to export auzre labels into yolo format or any other format?

### ISSUE THREAD

**Issue by aafaqin** [pylabel-project/samples#5]

**Comment by alexheat** [comment]
Hello. As far as I know there is no automatic way to do that. I think that you would need to write a custom exporter by iterating through your project and then saving the output into yolo format. You can see the API reference with the methods to get and export things from Azure Custom Vision

**Comment by aafaqin** [comment]
Thanks! I wrote my custom parser!

**Comment by alexheat** [comment]
Good job!
